"""
Crystal structure visualization module for CrystaLyse.AI.

This module provides comprehensive visualization capabilities for crystal structures
generated by the Chemeleon CSP tools. It supports multiple visualization backends
including py3Dmol for interactive 3D web visualizations and Plotly for custom
plotting needs.

Classes:
    CrystalVisualizer: Main visualization class with multiple backend support
    StructureStorage: File management and organization for crystal structures
    
Functions:
    create_visualization_report: Generate comprehensive HTML reports
    
Example:
    >>> from crystalyse.visualization import CrystalVisualizer
    >>> viz = CrystalVisualizer(backend="py3dmol")
    >>> view = viz.visualize_structure("structure.cif")
    >>> html_report = viz.create_multi_structure_report(structures, "CaTiO3")
"""

from .crystal_viz import CrystalVisualizer
from .storage import StructureStorage

__all__ = ['CrystalVisualizer', 'StructureStorage']